### PR TITLE
Bump version to 7.0

### PR DESCRIPTION
**Pull request by ewels**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Try to manually bump the version to v7.0, which is now on PyPI. It looks like the recent automated PRs have been failing, but the builds are no longer available. So if this fails then we can hopefully have a look at what is wrong.

### CODE REVIEW

**Comment by ewels** [comment]
@conda-forge-admin, please rerender

**Comment by ewels** [comment]
@conda-forge-admin, please add bot automerge

**Comment by ewels** [comment]
@conda-forge-admin, please ping team

**Comment by maxibor** [comment]
@conda-forge-admin, please ping team

**Comment by maxibor** [comment]
Sure

**Comment by ewels** [comment]
Thanks @beckermr!

**Pull request merged**
